function ZWaveCommandClasses() {
    var commandClasses = {
        'NO_OPERATION': 0,
        'BASIC': 32,
        'CONTROLLER_REPLICATION': 33,
        'APPLICATION_STATUS': 34,
        'ZIP_SERVICES': 35,
        'ZIP_SERVER': 36,
        'SWITCH_BINARY': 37,
        'SWITCH_MULTILEVEL': 38,
        //'SWITCH_MULTILEVEL_V2': 38
        'SWITCH_ALL': 39,
        'SWITCH_TOGGLE_BINARY': 40,
        'SWITCH_TOGGLE_MULTILEVEL': 41,
        'CHIMNEY_FAN': 42,
        'SCENE_ACTIVATION': 43,
        'SCENE_ACTUATOR_CONF': 44,
        'SCENE_CONTROLLER_CONF': 45,
        'ZIP_CLIENT': 46,
        'ZIP_ADV_SERVICES': 47,
        'SENSOR_BINARY': 48,
        'SENSOR_MULTILEVEL': 49,
        //'SENSOR_MULTILEVEL_V2': 49
        'METER': 50,
        'ZIP_ADV_SERVER': 51,
        'ZIP_ADV_CLIENT': 52,
        'METER_PULSE': 53,
        'METER_TBL_CONFIG': 60,
        'METER_TBL_MONITOR': 61,
        'METER_TBL_PUSH': 62,
        'THERMOSTAT_HEATING': 56,
        'THERMOSTAT_MODE': 64,
        'THERMOSTAT_OPERATING_STATE': 66,
        'THERMOSTAT_SETPOINT': 67,
        'THERMOSTAT_FAN_MODE': 68,
        'THERMOSTAT_FAN_STATE': 69,
        'CLIMATE_CONTROL_SCHEDULE': 70,
        'THERMOSTAT_SETBACK': 71,
        'DOOR_LOCK_LOGGING': 76,
        'SCHEDULE_ENTRY_LOCK': 78,
        'BASIC_WINDOW_COVERING': 80,
        'MTP_WINDOW_COVERING': 81,
        'ASSOCIATION_GRP_INFO': 89,
        'DEVICE_RESET_LOCALLY': 90,
        'CENTRAL_SCENE': 91,
        'IP_ASSOCIATION': 92,
        'ANTITHEFT': 93,
        'ZWAVEPLUS_INFO': 94,
        //'MULTI_CHANNEL_V2': 96,
        'MULTI_INSTANCE': 96,
        'DOOR_LOCK': 98,
        'USER_CODE': 99,
        'BARRIER_OPERATOR': 102,
        'CONFIGURATION': 112,
        'CONFIGURATION_V2': 112,
        'ALARM': 113,
        'MANUFACTURER_SPECIFIC': 114,
        'POWERLEVEL': 115,
        'PROTECTION': 117,
        //'PROTECTION_V2': 117,
        'LOCK': 118,
        'NODE_NAMING': 119,
        'FIRMWARE_UPDATE_MD': 122,
        'GROUPING_NAME': 123,
        'REMOTE_ASSOCIATION_ACTIVATE': 124,
        'REMOTE_ASSOCIATION': 125,
        'BATTERY': 128,
        'CLOCK': 129,
        'HAIL': 130,
        'WAKE_UP': 132,
        //'WAKE_UP_V2': 132,
        'ASSOCIATION': 133,
        'ASSOCIATION_V2': 133,
        'VERSION': 134,
        'INDICATOR': 135,
        'PROPRIETARY': 136,
        'LANGUAGE': 137,
        'TIME': 138,
        'TIME_PARAMETERS': 139,
        'GEOGRAPHIC_LOCATION': 140,
        'COMPOSITE': 141,
        //'MULTI_CHANNEL_ASSOCIATION_V2': 142,
        'MULTI_INSTANCE_ASSOCIATION': 142,
        'MULTI_CMD': 143,
        'ENERGY_PRODUCTION': 144,
        'MANUFACTURER_PROPRIETARY': 145,
        'SCREEN_MD': 146,
        //'SCREEN_MD_V2': 146,
        'SCREEN_ATTRIBUTES': 147,
        //'SCREEN_ATTRIBUTES_V2': 147,
        'SIMPLE_AV_CONTROL': 148,
        'AV_CONTENT_DIRECTORY_MD': 149,
        'AV_RENDERER_STATUS': 150,
        'AV_CONTENT_SEARCH_MD': 151,
        'SECURITY': 152,
        'AV_TAGGING_MD': 153,
        'IP_CONFIGURATION': 154,
        'ASSOCIATION_COMMAND_CONFIGURATION': 155,
        'SENSOR_ALARM': 156,
        'SILENCE_ALARM': 157,
        'SENSOR_CONFIGURATION': 158,
        'MARK': 239,
        'NON_INTEROPERABLE': 240
    };

    this.getCommand = function (number) {
        for (var propertyName in commandClasses) {
            if (commandClasses[propertyName] == number)
                return propertyName;
        }

        return number.toString();
    };
}

module.exports = new ZWaveCommandClasses();