function ZWaveCommandClasses() {
    var commandClasses = {
        'No Operation': 0,
        'Basic': 32,
        'Controller Replication': 33,
        'Application Status': 34,
        'ZIP Services': 35,
        'ZIP Server': 36,
        'Switch Binary': 37,
        'Switch Multilevel': 38,
        //'switch Multilevel v2': 38
        'Switch All': 39,
        'Switch Toggle Binary': 40,
        'Switch Toggle Multilevel': 41,
        'Chimney Fan': 42,
        'Scene Activation': 43,
        'Scene Actuator Configuration': 44,
        'Scene Controller Configuration': 45,
        'ZIP Client': 46,
        'ZIP Advanced Services': 47,
        'Sensor Binary': 48,
        'Sensor Multilevel': 49,
        //'Sensor Multilevel v2': 49
        'Meter': 50,
        'ZIP Adv Server': 51,
        'ZIP Adv client': 52,
        'Meter pulse': 53,
        'Meter Tbl config': 60,
        'Meter Tbl monitor': 61,
        'Meter Tbl push': 62,
        'Thermostat heating': 56,
        'Thermostat mode': 64,
        'Thermostat operating state': 66,
        'Thermostat setpoint': 67,
        'Thermostat fan mode': 68,
        'Thermostat fan state': 69,
        'Climate control schedule': 70,
        'Thermostat setback': 71,
        'Door Lock logging': 76,
        'schedule entry Lock': 78,
        'Basic window covering': 80,
        'mtp window covering': 81,
        'Association grp info': 89,
        'device reset locally': 90,
        'central scene': 91,
        'ip Association': 92,
        'antitheft': 93,
        'zwaveplus info': 94,
        //'Multi channel v2': 96,
        'Multi instance': 96,
        'Door Lock': 98,
        'User Code': 99,
        'Barrier Operator': 102,
        'Configuration': 112,
        //'Configuration v2': 112,
        'Alarm': 113,
        'Manufacturer Specific': 114,
        'Powerlevel': 115,
        'Protection': 117,
        //'protection v2': 117,
        'Lock': 118,
        'Node Naming': 119,
        'Firmware Update MD': 122,
        'Grouping Name': 123,
        'Remote Association Activate': 124,
        'Remote Association': 125,
        'Battery': 128,
        'CLock': 129,
        'Hail': 130,
        'Wake Up': 132,
        //'wake up v2': 132,
        'Association': 133,
        //'Association v2': 133,
        'Version': 134,
        'Indicator': 135,
        'Proprietary': 136,
        'Language': 137,
        'Alarm': 138,
        'Time paraMeters': 139,
        'Geographic Location': 140,
        'Composite': 141,
        //'Multi channel Association v2': 142,
        'Multi Instance Association': 142,
        'Multi cmd': 143,
        'Energy Production': 144,
        'Manufacturer Proprietary': 145,
        'Screen md': 146,
        //'screen md v2': 146,
        'Screen Attributes': 147,
        //'screen attributes v2': 147,
        'Simple AV Control': 148,
        'AV Content Directory md': 149,
        'AV Renderer Status': 150,
        'AV Content Search md': 151,
        'security': 152,
        'AV tagging md': 153,
        'ip Configuration': 154,
        'Association command Configuration': 155,
        'Sensor Alarm': 156,
        'Silence Alarm': 157,
        'Sensor Configuration': 158,
        'Mark': 239,
        'Non Interoperable': 240
    };

    this.getCommand = function (number) {
        for (var propertyName in commandClasses) {
            if (commandClasses[propertyName] == number)
                return propertyName;
        }

        return number.toString();
    };
}

module.exports = new ZWaveCommandClasses();