function ZWaveCommandClasses() {
    var commandClasses = {
        'No Operation': 0,
        'Basic': 32,
        'Controller Replication': 33,
        'Application Status': 34,
        'Zip Services': 35,
        'Zip Server': 36,
        'Switch Binary': 37,
        'Switch Multilevel': 38,
        //'switch multilevel v2': 38
        'Switch All': 39,
        'Switch Toggle Binary': 40,
        'Switch Toggle Multilevel': 41,
        'Chimney Fan': 42,
        'Scene Activation': 43,
        'Scene Actuator Configuration': 44,
        'Scene Controller Configuration': 45,
        'Zip Client': 46,
        'Zip Advanced Services': 47,
        'sensor binary': 48,
        'sensor multilevel': 49,
        //'sensor multilevel v2': 49
        'meter': 50,
        'zip adv server': 51,
        'zip adv client': 52,
        'meter pulse': 53,
        'meter tbl config': 60,
        'meter tbl monitor': 61,
        'meter tbl push': 62,
        'thermostat heating': 56,
        'thermostat mode': 64,
        'thermostat operating state': 66,
        'thermostat setpoint': 67,
        'thermostat fan mode': 68,
        'thermostat fan state': 69,
        'climate control schedule': 70,
        'thermostat setback': 71,
        'door lock logging': 76,
        'schedule entry lock': 78,
        'basic window covering': 80,
        'mtp window covering': 81,
        'association grp info': 89,
        'device reset locally': 90,
        'central scene': 91,
        'ip association': 92,
        'antitheft': 93,
        'zwaveplus info': 94,
        //'multi channel v2': 96,
        'multi instance': 96,
        'door lock': 98,
        'user code': 99,
        'barrier operator': 102,
        'configuration': 112,
        'configuration v2': 112,
        'alarm': 113,
        'manufacturer specific': 114,
        'powerlevel': 115,
        'protection': 117,
        //'protection v2': 117,
        'lock': 118,
        'node naming': 119,
        'firmware update md': 122,
        'grouping name': 123,
        'remote association activate': 124,
        'remote association': 125,
        'battery': 128,
        'clock': 129,
        'hail': 130,
        'wake up': 132,
        //'wake up v2': 132,
        'association': 133,
        //'association v2': 133,
        'version': 134,
        'indicator': 135,
        'proprietary': 136,
        'language': 137,
        'time': 138,
        'time parameters': 139,
        'geographic location': 140,
        'composite': 141,
        //'multi channel association v2': 142,
        'multi instance association': 142,
        'multi cmd': 143,
        'energy production': 144,
        'manufacturer proprietary': 145,
        'screen md': 146,
        //'screen md v2': 146,
        'screen attributes': 147,
        //'screen attributes v2': 147,
        'simple av control': 148,
        'av content directory md': 149,
        'av renderer status': 150,
        'av content search md': 151,
        'security': 152,
        'av tagging md': 153,
        'ip configuration': 154,
        'association command configuration': 155,
        'sensor alarm': 156,
        'silence alarm': 157,
        'sensor configuration': 158,
        'mark': 239,
        'non interoperable': 240
    };

    this.getCommand = function (number) {
        for (var propertyName in commandClasses) {
            if (commandClasses[propertyName] == number)
                return propertyName;
        }

        return number.toString();
    };
}

module.exports = new ZWaveCommandClasses();